### ISSUE TITLE
ability to place gohack files inside module directory instead of $HOME

### ISSUE THREAD

**Issue by b0o** [rogpeppe/gohack#27]
I haven't tried gohack yet, but I am curious about this scenario which I have encountered when doing a similar thing manually:

I have two separate projects (let's call them `myProjectA` and `myProjectB`), each of which happen to use the `github.com/jmoiron/sqlx` package.

For project `myProjectA`, I discover a need to modify function `f` of `sqlx`, so I use gohack to get a  mutable copy of the repo, and make my changes.

For project `myProjectB`, I want to use the original unmodified version of `sqlx`, but I want to place a `log.Printf(...)` statement inside function `g` of `sqlx`. If I were to use gohack to replace `sqlx` in this project, my understanding is that project `myProjectB` would begin using the same copy of `sqlx` as project `myProjectA`.

Is my reasoning correct? 

If so, a way to avoid this seems to be to place gohack'd packages inside, say, `myProjectA/.gohack/github.com/jmoiron/sqlx`. This may also resolve #5?

I suppose the main issues with this are:
- Having a git repo within a git repo - however, the `.gohack` directory would most likely be included in `.gitignore`
- More difficult to use the same gohack'd package across multiple modules

**Comment by rogpeppe** [comment]
Thanks for raising this issue. Storing all gohacked modules locally to a project was actually the first approach I considered. I decided against it because I wanted it to be straightforward to turn changes to gohacked modules into PRs or to be able to easily save the code. With a local gohack directory, every time you ran gohack from a new project, you would need to set up a git remote to point to your fork of the repo, for example.

Instead, I considered that it was probably better to keep them in a well known place, not separately inside each project. That way any code you've written can easily be stashed and found again, and your remotes only need to be set up once.

When you gohack a module, gohack does give an error if that module has been edited since it was gohacked (and avoids checking out the current version in that case), so at least you know when you're not using the correct version.

You can set the $GOHACK environment variable if you want the files to go in a different place. One possible idea would be to specify that a non-absolute $GOHACK path would be interpreted relative to the current module's root directory. That would make it easy to achieve your suggestion.

Please try out gohack and provide feedback. There are lots of arbitrary decisions in its design which can only be validated by real work use.

**Comment by mortyccp** [comment]
It will be useful for situation using docker-compose for development.  
Since we cannot mount volume outside of build context. A way to store gohacked modules locally will great.

**Comment by rogpeppe** [comment]
You can set the GOHACK environment variable to the name of any directory. Does that fulfill your requirements here?

**Comment by mortyccp** [comment]
Yes, I think `GOHACK=$(pwd) gohack ...` will work.

**Comment by rogpeppe** [comment]
but see also issue #35.

**Comment by mortyccp** [comment]
There problem I encounter using `GOHACK=./hack gohack ...` is that the replace path is missing the `./`. I think implementing what you suggested about non-absolute path is valuable.

**Comment by davidovich** [comment]
I believe this can now be closed by #45, as setting a relative directory in the GOHACK env var is now supported.

**Comment by myitcv** [comment]
Agreed. @b0o @mortyccp please shout if you disagree and we can re-open.
